name: autotests

on:
    push:
        branches: [ main, master ]
    pull_request:
        branches: [ main, master ]

jobs:

  microservicestest:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck on auth service
        run: |
          cd auth
          staticcheck ./...

      - name: Run staticcheck on chat-server service
        run: |
          cd chat-server
          staticcheck ./...

      - name: Run vet on auth service
        run: |
          cd auth
          go vet ./...

      - name: Run vet on chat-server service
        run: |
          cd chat-server
          go vet ./...

      - name: Run golangci-lint on auth service
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: microservices/auth

      - name: Run golangci-lint on chat-server service
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: microservices/chat-server
